/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hexoct.h"

char **
tohex_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	 result = (char*)malloc(sizeof(char) * 50);
	 sprintf(result, "%x", *argp);
	 printf("Converted Hex: %s\n", result);

	return &result;
}

int *
tooct_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 int num = *argp;
	 int rem, oct = 0, e = 1;

	 while(num > 0){
		 rem = num % 8;
		 oct = rem * e + oct;
		 e = e * 10;
		 num = num / 8;
	 }
	 result = oct;

	 printf("converted Oct: %d\n", result);
	return &result;
}
