/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hexoct.h"


void
hexoct_1(char *host)
{
	int num;
	printf("Enter a number\n");
	scanf("%d", &num);

	CLIENT *clnt;
	char * *result_1;
	int  tohex_1_arg = num;
	int  *result_2;
	int  tooct_1_arg = num;

#ifndef	DEBUG
	clnt = clnt_create (host, hexoct, hexoct1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = tohex_1(&tohex_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Hex number %s\n", *result_1);

	result_2 = tooct_1(&tooct_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Oct number %d\n", *result_2);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	hexoct_1 (host);
exit (0);
}
